version: '2'

services:

# ### MySQL Container #########################################

    mysql:
        image: mysql:5.7.17
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: tWU33HaRfhQxzt9Y
